---
#we include in case this was included manually from a tasks file
- name: include defaults
  include_vars: ../defaults/main.yml
  tags: ['install_packages']

- name: Ensure Tomcat6 packages are installed (yum).
  tags:  install_packages
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - libmysql-java
    - tomcat6
    - tomcat6-webapps
    - tomcat6-admin-webapps
  when: "ansible_pkg_mgr == 'yum'"  
  tags: ['install_packages']
  
- name: Ensure Tomcat6 is installed (apt).
  tags:  install_packages
  apt:
    name: "{{ item }}"
    state: latest
  when: ansible_pkg_mgr == 'apt'
  with_items:
    - tomcat6
    - tomcat6-admin 
    - tomcat6-common 
    - tomcat6-user 
    - tomcat6-docs 
    - tomcat6-examples
  tags: ['install_packages']
  
- name: Copy /etc/default/tomcat
  template:
    src: etc/default/tomcat6
    dest: /etc/default/tomcat6
    owner: root
    group: root
    mode: 0644
  tags: ['install_packages']
  
- name: Copy tomcat6 server.xml.
  template:
    src: server.xml
    dest: /etc/tomcat6/server.xml
    owner: root
    group: root
    mode: 0644
  tags: ['install_packages']
     

- name: restart tomcat
  service: name=tomcat6 state=restarted  
  
- name: Ensure tomcat6 is running.
  service:
    name: tomcat6
    state: started
    enabled: yes
  when: tomcat6_enabled
