---

# no need on debian - already in main repos    
- name: Add MariaDB apt key (apt)
  apt_key: url=http://keyserver.ubuntu.com/pks/lookup?op=get&fingerprint=on&search=0xcbcb082a1bb943db
  when: "ansible_pkg_mgr=='apt' "
  
- name: Add MariaDB apt repository (apt)
  apt_repository: repo='deb http://ftp.osuosl.org/pub/mariadb/repo/5.5/{{ ansible_distribution|lower}} {{ ansible_lsb.codename }} main' update_cache=yes
  when: "ansible_pkg_mgr=='apt' "
   
- name: debug vars
  debug: var={{item}}    
  with_items:
    - ansible_distribution
    - mariadb_repo_subpath_distrib
    - mariadb_repo_subpath_os_version
    - mariadb_repo_subpath
    - db_version
    - yum_mariadb_repo_gpg_key_url
    
# - fail:    
    
- name: Install mariadb repo. (yum)
  tags:  install_packages
  template:
    src: "{{ansible_root_dir}}/roles/database/templates/mariadb.repo"
    dest: "/etc/yum.repos.d/mariadb-{{db_version}}.repo"
    owner: root
    mode: "0640"
  when: "ansible_pkg_mgr=='yum'"
  
- name: Import mariadb GPG key. (yum)
  tags:  install_packages
  rpm_key:
    key: "{{ yum_mariadb_repo_gpg_key_url }}"
    state: present
    validate_certs: no
  when: "ansible_pkg_mgr=='yum'"  
  
- name: remove mysql server (apt)
  apt: name={{ item}} state=absent force=yes
  # tags:  [ 'mysql', 'database' ]
  with_items:
    - mysql-*
  when: "ansible_pkg_mgr == 'apt'"
  
- name: remove mysql server (yum)
  action: "{{ ansible_pkg_mgr }} name={{ item }} state=absent"
  tags:  install_packages
  # tags:  [ 'mysql', 'database' ]
  with_items:
    - mysql-*
  when: "ansible_pkg_mgr == 'yum'"
  ignore_errors: true
   
- name: Install mariadb server (apt)
  apt: name={{ item}} state={{installed_package_state}} force=yes
  notify:
    # - update-rc mysql
    - mysql restart
  tags:  install_packages
  with_items:
    - mariadb-server-{{ db_version }}
    - python-mysqldb
  when: "ansible_pkg_mgr == 'apt'"
  ignore_errors: true
  
- name: Install mariadb server (yum)
  action: "{{ ansible_pkg_mgr }} name={{ item }} state=present"
  tags:  install_packages
  when: "ansible_pkg_mgr == 'yum'"
  with_items:
    - MariaDB-server
    - MariaDB-client
    - MySQL-python

    # path: /etc/systemd/system/multi-user.target.wants/mysql.service
    # state: link
    # force: yes
  # when: mariadb_service_exists.stat.exists    
  
# - name: ensure mariadb service is stopped so no conflict when we start mysql service
  # service: name=mariadb state=stopped enabled=no
  # when: mariadb_service_exists.stat.exists    
  
