---
    
- name: Install Percona GPG key
  apt_key: data="{{ lookup('file', '../templates/percona-gpg-key') }}"
  when: "db_type=='mysql' and db_variant=='percona'"
  # tags:  [ 'percona', 'database' ]
    
- name: Enable Percona repo
  apt_repository: repo='deb http://repo.percona.com/apt {{ ansible_lsb.codename }} main' state=present update_cache=yes
  when: "db_type=='mysql' and db_variant=='percona'"
  # tags:  [ 'percona', 'database' ]

  
- name: Install percona server (apt)
  apt: name={{ item}} state={{installed_package_state}} force=yes
  notify:
    # - update-rc mysql
    - mysql restart
  tags:  install_packages
  with_items:
    - percona-server-server-5.6
    # - percona-server-client-5.6
    - python-mysqldb
  when: "ansible_pkg_mgr == 'apt'"
  
- name: Install percona server (yum)
  action: "{{ ansible_pkg_mgr }} name={{ item }} state=present"
  tags:  install_packages
  when: "ansible_pkg_mgr == 'yum'"
  with_items:
    - percona-server-server-5.6
    # - percona-server-client-5.6    
    - MySQL-python
    
