---
# ==============
# ClusterControl
# ==============

clustercontrol_install_use_shell_script: true

clustercontrol_ui_packages:
  - clustercontrol-cmonapi
  - clustercontrol
  - clustercontrol-nodejs
clustercontrol_controller_packages:
  - clustercontrol-controller
cmon_config_file: /etc/cmon.cnf
cmon_sql_path: /usr/share/cmon
cmonapi_bootstrap: "{{ cc_www_root }}/cmonapi/config/bootstrap.php"
cmonapi_database: "{{ cc_www_root }}/cmonapi/config/database.php"
ccui_bootstrap: "{{ cc_www_root }}/clustercontrol/bootstrap.php"

cmon_mysql_password: "{{ webapps_default_db_user_password}}"
cmon_mysql_port: "{{db.mysql_listen_port}}"
cmon_ssh_user: root
cmon_ssh_key_path: /root/.ssh/id_rsa
cmon_ssh_key_dir: /root/.ssh
rpc_url: http://{{lb.external_bind_address}}:9500
gpg_key: http://repo.severalnines.com/severalnines-repos.asc

## Default User ##

# Define admin email address.
cc_admin:
 - email: "{{admin_email}}"
   password: "{{admin_userpassword}}"

# ===============================
# MySQL/MariaDB on ClusterControl
# ===============================

# Set this to `yes` to forcibly update the root password.
mysql_root_secure_password_update: yes
mysql_enabled_on_startup: yes
overwrite_global_mycnf: yes

# MySQL connection settings.
mysql_port: "{{ cmon_mysql_port }}"
mysql_bind_address: "{{db.mysql_listen_addr}}"
mysql_datadir: /var/lib/mysql
mysql_pid_file: "{{ mysql_datadir }}/mysql.pid"
mysql_user_home: /root

# Memory settings (default values optimized ~512MB RAM).
mysql_key_buffer_size: "32M"
mysql_max_allowed_packet: "16M"
mysql_table_open_cache: "256"
mysql_sort_buffer_size: "1M"
mysql_read_buffer_size: "1M"
mysql_read_rnd_buffer_size: "4M"
mysql_thread_cache_size: "16"
mysql_max_connections: 151
mysql_wait_timeout: 28800
mysql_thread_concurrency: 2
mysql_mysqldump_max_allowed_packet: "64M"

# InnoDB settings.
mysql_innodb_file_per_table: "1"
mysql_innodb_additional_mem_pool_size: "20M"
mysql_innodb_log_file_size: "64M"
mysql_innodb_log_buffer_size: "8M"
mysql_innodb_flush_log_at_trx_commit: "1"
mysql_innodb_lock_wait_timeout: 50

# MySQL Users.
mysql_users:
  - name: cmon
    host: "{{ db.mysql_listen_addr }}"
    password: "{{ cmon_mysql_password }}"
    priv: "*.*:ALL,GRANT"
  - name: cmon
    host: "{{ ansible_fqdn }}"
    password: "{{ cmon_mysql_password }}"
    priv: "*.*:ALL,GRANT"
  - name: cmon
    host: "localhost"
    password: "{{ cmon_mysql_password }}"
    priv: "*.*:ALL,GRANT"


## License ##

# If you have a valid license, define them here:
# cc_license:
#   - email: "demo@severalnines.com"
#     company: "Severalnines AB"
#     expired_date: "31/12/2017"
#     key: "XXXXXXXXXXXXXXXXXXXXXXXX"

## LDAP (experimental)##

# If you would like to integrate LDAP authentication with ClusterControl,
# define the settings here:
# cc_ldap:
#   - enabled: 1
#     host: "192.168.1.100"
#     port: 389
#     base_dn: "dc=mydomain,dc=com"
#     admin_dn: "cn=admin,dc=mydomain,dc=com"
#     admin_password: "password"
#     user_dn: "ou=People,dc=mydomain,dc=com"
#     group_dn: "ou=Group,dc=mydomain,dc=com"

## Database Cluster ##

# If you would like to add or create database host or cluster, set
# 'deployment: true' and define the variables here. If true, the role
# will always send the deployment job to CMON regardless the database
# cluster is already deployed or not. It's recommended to set it to false
# once the cluster is successfully created. ClusterControl will deploy/import
# the cluster including setting up the passwordless SSH:

# cc_cluster:
# 	- deployment: true
#     operation: add
# 	  type: galera
# 		vendor: percona
# 	  mysql_hostnames:
#       - '192.168.1.171'
#       - '192.168.1.172'
#       - '192.168.1.173'
# 		mysql_port: 3306
# 		mysql_user: "root"
# 	  mysql_password: "mypassword"
# 		ssh_user: "root"
# 		ssh_keyfile: "/root/.ssh/id_rsa"
# 		ssh_port: 22
# 		sudo_password: ""
#     enable_node_autorecovery: true
#     enable_cluster_autorecovery: true
# 	- deployment: true
#     operation: create
# 	  type: replication
# 	  mysql_version: "5.7"
#     mysql_cnf_template: "my.cnf.repl57"
#     mysql_datadir: "/var/lib/mysql"
# 		vendor: oracle
# 		mysql_hostnames:
#       - '192.168.55.16'
#       - '192.168.55.17'
# 		mysql_port: 3306
# 		mysql_user: "root"
# 		mysql_password: "mypassword"
# 		ssh_user: "root"
# 		ssh_keyfile: "/root/.ssh/id_rsa"
# 		ssh_port: 22
# 		sudo_password: ""

# =================
# Managed DB nodes
# =================
ssh_key_dir: /root/.ssh
ssh_user: root
