---
- hosts: all
  # ### remote_user: vagrant
  serial: "{{serial_var}}"
  #allow 2 out of 3 to fail while downloading packages to shared host directory
  max_fail_percentage: 1
  sudo: yes

  vars_files:
    - "{{pb_app_vars_file}}" #parsed from extra args in config.yml
    - "{{pb_config_vars_file}}" #parsed from extra args in config.yml
    - "{{pb_site_vars_file}}" #parsed from extra args in config.yml

  vars:


  pre_tasks:


  roles:
    - {
      role: upgrade_distrib,
      when: upgrade_distrib_to_latest is defined and upgrade_distrib_to_latest
    }
    - handlers
    - {
        role: docker,
        when: is_server_monitor
      }
    - {
        role: nginx,
        when: is_server_monitor
      }
    - {
        role: zabbix-agent,
        when: True
      }
    - {
        role: zabbix-server,
        when: is_server_monitor
      }
    - {
          role: grafana,
          when: is_server_monitor
      }
#    - {
#        role: prometheus,
#        prometheus_components: [ "prometheus", "node_exporter", "mysqld_exporter", "alertmanager" ],
#        when: is_server_monitor
#      }
#    - {
#        role: prometheus,
#        prometheus_components: [ "node_exporter", "mysqld_exporter"],
#        when: not is_server_monitor
#      }
#    - {
#        role: graphite,
#        when: is_server_monitor
#      }


