---
- name: Run YUM Specific Tasks 
  include: yum.yml
  when: "ansible_pkg_mgr=='yum'"
  tags: ['always']
  
- name: Run APT Specific Tasks 
  include: apt.yml
  when: "ansible_pkg_mgr=='apt'"
  tags: ['always']
  