- name: Gather Default Variables
  tags: ['always']
  include_vars: "{{ item }}"
  with_first_found: #from more specific to less specific - ?the more specific file could in turn include less specific files?
    - "../vars/default.yml"
    
- debug: var=php7_major_version

# create opcache file cache dir
- file: path={{ opcache_file_cache_path }} state=directory owner={{web_user }}  group={{ web_group}}
  tags: ['always']

- name: Run APT Specific Tasks 
  tags: ['always']
  include: apt.yml
  when: "ansible_pkg_mgr=='apt'"
  
- name: Run YUM Specific Tasks 
  tags: ['always']
  include: yum.yml
  when: "ansible_pkg_mgr=='yum'"


