---

##### clustercontrol templates for zabbix ##############
- name: install clustercontrol templates for zabbix
  shell: "cd /tmp && rm -Rf ./s9s-admin && git clone https://github.com/severalnines/s9s-admin && mkdir -p /etc/zabbix/zabbix_agentd.d && /bin/cp -f ./s9s-admin/plugins/zabbix/agent/userparameter_clustercontrol.conf /etc/zabbix/zabbix_agentd.d/ && mkdir -p /var/lib/zabbix/clustercontrol && /bin/cp -Rf ./s9s-admin/plugins/zabbix/agent/scripts /var/lib/zabbix/clustercontrol;"
  ignore_errors: yes #incase already created in same task running on same pc when running many roles-types in local mode

- name: configure zabbix access to cc api
  blockinfile:
    dest: /var/lib/zabbix/clustercontrol/scripts/clustercontrol.conf
    marker: "# {mark} ANSIBLE MANAGED BLOCK: ccapi #"
    block: |
          ccapi_url='{{cmonapi_external_url}}'
          ccapi_token='{{cmon_api_rpc_token}}'
          ## how to get ccapi_token - run on server monitor
          # docker exec -it {{cluster_control_docker_container_name}} /bin/bash
          # cat /etc/cmon.cnf | grep 'rpc_key' | awk -F'=' '{print $2}'
    create: yes
    backup: yes
#
#- name: configure zabbix access to cc api - how to find the api token?
#  shell: echo "If you do not configure this correctly, the script will not work. You can retrieve the API token value at {Apache Document Root}/cmonapi/config/bootstrap.php on the ClusterControl node \n OR \n docker exec -i cluster_controller /bin/bash -c \"cat /etc/cmon.cnf | grep 'rpc_key' | awk -F'=' '{print $2}' \"
#  "

#- name: test the script
#  shell: "/var/lib/zabbix/clustercontrol/scripts/clustercontrol_stats.sh 1 test; \n if this returns an error,Invalid access token or access token is not configured correctly \n docker exec -it cluster_control /bin/bash \n    nano  /var/www/html/cmonapi/config/bootstrap.php \n   define('ENABLE_CC_API_TOKEN_CHECK', '1'); change '1' to '0'   "
#
#
#
#
#
#
