---
- name: restart apache
  service: name={{ apache_service }} state=restarted

- name: restart carbon-cache
  service: name=carbon-cache state=restarted


- name: restart uwsgi
  service: name=uwsgi state=restarted
