# file: maxscale-deb.yml 
  
- name: install maxscale repo
  apt: name=http://downloads.mariadb.com/enterprise/{{ enterprise_token }}/generate/10.0/mariadb-enterprise-repository.deb state=present
  tags:  install_packages

- name: install maxscale
  apt: name=maxscale state=present
  tags:  install_packages
