- name: upgrade to latest distrib disabling presto as it can fail for some repos like epel and percona
  shell: yum upgrade --setopt=deltarpm=0 --assumeyes --tolerant
  tags:
     - install_packages

- name: Check if the kernel is at least 3.10
  shell: uname -r | grep "^3.10."
  register: uname_result
  tags:
     - always

- name: Enable OverlayFS before rebooting to avoid another reboot for docker!
  template:
    src: overlay.conf
    dest: /etc/modules-load.d/overlay.conf
  when: uname_result.stdout != ''
  tags:
     - always

- name: Check for reboot hint.
  shell: LAST_KERNEL=$(rpm -q --last kernel | perl -pe 's/^kernel-(\S+).*/$1/' | head -1); CURRENT_KERNEL=$(uname -r); if [ $LAST_KERNEL != $CURRENT_KERNEL ]; then echo 'reboot'; else echo 'no'; fi
  ignore_errors: true
  register: reboot_hint
  tags:
     - always

- name: restart server {{ ansible_host }}
  command: shutdown -r now "Ansible updates triggered"
  async: 0
  poll: 0
  when: reboot_hint.stdout.find("reboot") != -1
  register: rebooting
  tags:
     - always


- name: wait for server {{ ansible_host }} to come back
  local_action: wait_for host={{ ansible_host }} port=22 state=started delay=30 timeout=90
  become: false
  when: reboot_hint.stdout.find("reboot") != -1
  tags:
     - install_packages

