- name: check if key file exists
  stat:
    path: ~/.ssh/id_rsa
  register: id_rsa_exists

- name: Generate SSH key
  shell: ssh-keygen -b 2048 -t rsa -f ~/.ssh/id_rsa -q -N ""
  args:
    creates: ~/.ssh/id_rsa
  when: not id_rsa_exists.stat.exists

- name: push ssh key to all hosts in run
  authorized_key:
    user: root
    key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"
  become: yes


