---
munin_packages:
  - python-passlib
  - munin
  - munin-node
  

munin_conf_d_directory: /etc/munin/conf.d

munin_dbdir: /var/lib/munin
munin_htmldir: /var/www/html
munin_logdir: /var/log/munin
munin_rundir: /var/run/munin

munin_port: 4949

munin_includedir: /etc/munin/conf.d

munin_html_strategy: cron
munin_cron_job: present

munin_max_processes: 12

munin_admin_user: munin
munin_admin_password: munin

# Will be translated into:
# [host]
#   address: [name]
#   [extra.0]
#   [extra.1]
#   [...]
#
# Note that `name` can be hostname, or group + hostname, for example:
# [example.com;foo.example.com]
munin_hosts:
  # - {
    # name: "localhost",
    # address: "127.0.0.1",
    # extra: ["use_node_name yes"]
  # }

#note: ensure no space in munin_alerts:name 
munin_alerts: 
 - {
   name: "Administrator@{{ansible_hostname}}",
   email: "{{admin_email}}",
   subject: "Munin-notification for ${var:group} :: ${var:host}",
   level: "warning critical"
  }

