---
# sumeet - done in common.ym-cluter_db
#- name: Copy my.cnf global MySQL configuration.
#  template:
#    src: my.cnf
#    dest: "{{ mysql_config_file }}"
#    owner: root
#    group: root
#    mode: 0644
#    force: "{{ overwrite_global_mycnf }}"
#  notify: restart mysql
#
#- name: Ensure MySQL is started and enabled on boot.
#  service: "name={{ mysql_daemon }} state=started enabled={{ mysql_enabled_on_startup }}"
#  register: mysql_service_configuration
#  ignore_errors: true #as rhel start command hangs even though successful
