---
# Include variables and define needed variables.
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"
  tags:
    - always

- name: Include RHEL >= 7 specific variables.
  include_vars: "RedHat7.yml"
  when: ansible_os_family == 'RedHat' and ansible_distribution_major_version|int >= 7
  tags:
    - always

- name: Include Debian >= 8 specific variables.
  include_vars: "Debian8.yml"
  when:
    (ansible_distribution == 'Debian' and ansible_distribution_major_version|int > 7) or
    (ansible_distribution == 'Ubuntu' and ansible_distribution_major_version|int > 12)
  tags:
    - always


#always create nginx virtual host so we can switch fromapache to nginx even if installing from script
- name: Configure /etc/nginx/conf.d/clustercontrol.conf
  template: src=cc.nginx.conf dest=/etc/nginx/conf.d/clustercontrol.conf owner=root group=root mode=0644
#  notify: nginx restart #do not restart as httpd may be running - just copy vhost file
  ignore_errors: yes
  tags:
    - always


#############
- name: ask user to install clustercontrol using shell script
  shell: echo "service nginx stop;cd /tmp; mkdir -p cc; cd cc;wget http://www.severalnines.com/downloads/cmon/install-cc;chmod +x install-cc;./install-cc"
  ignore_errors: no
  tags:
    - install_packages
#############
