---
# file: tasks/install-node-exporter.yml
#
# Install Prometheus node-exporter.
#
# @see http://prometheus.io/docs/introduction/getting_started/
#

- block:

    - name: set internal variables for convenience
      set_fact:
        prometheus_mysqld_exporter_tarball_url: "https://github.com/prometheus/mysqld_exporter/releases/download/{{ prometheus_mysqld_exporter_version }}/mysqld_exporter-{{ prometheus_mysqld_exporter_version }}.linux-amd64.tar.gz"
        prometheus_mysqld_exporter_subdir: "{{ prometheus_install_path }}/mysqld_exporter-{{ prometheus_mysqld_exporter_version }}.linux-amd64"
      when: ansible_userspace_bits == "64"

    - name: set internal variables for convenience
      set_fact:
        prometheus_mysqld_exporter_tarball_url: "https://github.com/prometheus/mysqld_exporter/releases/download/{{ prometheus_mysqld_exporter_version }}/mysqld_exporter-{{ prometheus_mysqld_exporter_version }}.linux-386.tar.gz"
        prometheus_mysqld_exporter_subdir: "{{ prometheus_install_path }}/mysqld_exporter-{{ prometheus_mysqld_exporter_version }}.linux-386"
      when: ansible_userspace_bits == "32"

    - name: set daemon dir for >= 0.12
      set_fact:
        prometheus_mysqld_exporter_daemon_dir: "{{ prometheus_mysqld_exporter_subdir }}"
      when: prometheus_mysqld_exporter_version | version_compare('0.12', '>=')

    - name: set daemon dir for < 0.12
      set_fact:
        prometheus_mysqld_exporter_daemon_dir: "{{ prometheus_install_path }}"
      when: prometheus_mysqld_exporter_version | version_compare('0.12', '<')

  when: prometheus_mysqld_exporter_version != "git"
  tags:
      - always

- block:
    - name: download and untar mysqld_exporter tarball
      unarchive:
        src: "{{ prometheus_mysqld_exporter_tarball_url }}"
        dest: "{{ prometheus_install_path }}"
        copy: no

  when: prometheus_mysqld_exporter_version != "git"
  tags:
      - install_packages


- block:

    - name: set internal variables for convenience
      set_fact:
        prometheus_mysqld_exporter_git_url: "https://github.com/prometheus/mysqld_exporter.git"
        prometheus_mysqld_exporter_src_path: "{{ prometheus_goroot }}/src/github.com/prometheus/mysqld_exporter"
        prometheus_mysqld_exporter_daemon_dir: "{{ prometheus_install_path }}"

    - name: delete the mysqld_exporter build directory, if necessary
      file: path={{ prometheus_mysqld_exporter_src_path }}  state=absent
      when: prometheus_rebuild

    - name: mkdir for mysqld_exporter source code
      file: path={{ prometheus_mysqld_exporter_src_path }}  state=directory

    - name: clone the mysqld_exporter project src
      git:
        repo: "{{ prometheus_mysqld_exporter_git_url }}"
        dest: "{{ prometheus_mysqld_exporter_src_path }}"
        force: yes

    - name: build mysqld_exporter source code
      command: make
      args:
        chdir: "{{ prometheus_mysqld_exporter_src_path }}"
        creates: mysqld_exporter
      environment:
        GO15VENDOREXPERIMENT: 1
        GOROOT: "{{ prometheus_goroot }}"
        GOPATH: "{{ prometheus_gopath }}"
        PATH: "{{ ansible_env.PATH }}:{{ prometheus_goroot }}/bin:{{ prometheus_gopath }}/bin"

    - name: copy the built mysqld_exporter to the install path
      command: "cp {{ prometheus_mysqld_exporter_src_path }}/mysqld_exporter {{ prometheus_install_path }}"
      args:
        creates: "{{ prometheus_install_path }}/mysqld_exporter"

  when: prometheus_mysqld_exporter_version == "git"
  tags:
      - install_packages


- name: set permissions, owner and group
  file: path={{ prometheus_mysqld_exporter_daemon_dir }}/mysqld_exporter owner={{ prometheus_user }} group={{ prometheus_group }} mode="go-w"
  tags:
    - always

- name: mkdir for data
  file:
    path: "{{ prometheus_db_path }}"
    state: directory
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_group }}"
    mode: "u=rwx,g=rx,o="
  tags:
    - always

- name: set mysqld_exporter variables
  copy: src="../files/etc-default-mysqld-exporter"  dest=/etc/default/mysqld_exporter
  tags:
    - always


- name: configure /home/prometheus/.my.cnf for mysqld_exporter
  template:
    src: ../../zabbix-agent/templates/user_zabbix.my.cnf
    dest: "~{{ prometheus_user }}/.my.cnf"
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_group }}"
  tags:
    - always


- name: copy INIT script to server
  template: src="../templates/mysqld_exporter.sysvinit.{{ ansible_os_family|lower }}.sh"  dest="/etc/init.d/mysqld_exporter"  mode="a+x"
  when: not prometheus_mysqld_exporter_use_systemd|bool
  tags:
    - always

- name: copy systemd config to server
  template: src="../templates/mysqld_exporter.service"  dest="/lib/systemd/system/mysqld_exporter.service"
  when: prometheus_mysqld_exporter_use_systemd
  tags:
    - always
    


- name: make config for nginx
  template: src=nginx-mysqld_exporter.conf
            dest=/etc/nginx/conf.d/mysqld_exporter.conf
            owner={{web_user}}
            mode=0644
  notify:
    - nginx restart
  tags:
    - always
    

- name: set INIT status and start
  service: name=mysqld_exporter enabled=yes state=restarted
  ignore_errors: true
  tags:
    - always
