---

- name: Configuring
  template:
    src: "{{ openssl_config_template if openssl_config_template else 'etc-ssl-openssl.cnf' }}"
    dest: /etc/ssl/openssl.cnf
    owner: root
    group: root
    mode: 0644
