---
# file: handlers/main.yml
#

- name: restart prometheus
  service: name=prometheus state=restarted
  when: prometheus_use_service|bool
  ignore_errors: true

- name: reload prometheus
  service: name=prometheus state=reloaded
  when: prometheus_use_service|bool
  ignore_errors: true

- name: stop prometheus
  service: name=prometheus state=stopped
  when: prometheus_use_service|bool
  ignore_errors: true



- name: restart node_exporter
  service: name=node_exporter state=restarted
  ignore_errors: true

- name: reload node_exporter
  service: name=node_exporter state=reloaded
  ignore_errors: true

- name: stop node_exporter
  service: name=node_exporter state=stopped
  ignore_errors: true



- name: restart alertmanager
  service: name=alertmanager state=restarted
  when: prometheus_use_service|bool
  ignore_errors: true

- name: reload alertmanager
  service: name=alertmanager state=reloaded
  when: prometheus_use_service|bool
  ignore_errors: true

- name: stop alertmanager
  service: name=alertmanager state=stopped
  when: prometheus_use_service|bool
  ignore_errors: true
