---
 
# - name: set user passwds
#   user: name={{item.name}} state=present password={{item.password}} update_password=always
#   with_items:
#    - {name: "root", password: "{{ root_securepassword|password_hash('sha512') }}"  }
#    - {name: "vagrant", password: "{{ vagrant_securepassword|password_hash('sha512') }}"  }
#   ignore_errors: false
 
 - name: unlock root login
   shell: "passwd -f -u {{item.name}}"
   with_items:
    - {name: "root"}
   ignore_errors: true #incase already created in same task running on same pc when running many roles-types in local mode
  
 - name: allow root ssh  
   lineinfile: 
      dest: /etc/ssh/sshd_config
      regexp: "PermitRootLogin"
      state: absent
      
 - name: allow root ssh  
   lineinfile: 
      dest: /etc/ssh/sshd_config
      regexp: "PermitRootLogin"
      line: "PermitRootLogin yes"
      state: present
      
 - name: allow ansible git clone behind firewall
   shell: git config --global url."https://".insteadOf git://
   ignore_errors: true

