---
# defaults file for zabbix-agent

zabbix_version: 3.0
zabbix_repo: zabbix
zabbix_agent_package: zabbix-agent
zabbix_agent_package_state: present # or latest

agent_server: "{{lb.server_monitor_1_external_addr}}"
agent_serveractive: "{{lb.server_monitor_1_external_addr}}:{{zabbix_server_listenport}}"

agent_listenip: 0.0.0.0

agent_listeninterface:

# Zabbix API stuff
zabbix_api_user: Admin
zabbix_api_pass: "{{zabbix_adminuser_password}}"
zabbix_api_create_hostgroup: False
zabbix_api_create_hosts: False
zabbix_create_hostgroup: present  # or absent
zabbix_create_host: present       # or absent
zabbix_host_status: enabled       # or disabled
zabbix_proxy: null
zabbix_useuip: 1
zabbix_host_groups:
  - Linux servers
zabbix_link_templates:
  - Template OS Linux

agent_interfaces:
  - type: 1
    main: 1
    useip: "{{ zabbix_useuip }}"
    ip: "{{ agent_ip }}"
    dns: "{{ ansible_fqdn }}"
    port: "{{ zabbix_agent_listenport }}"

# Zabbix configuration variables
agent_pidfile: /var/run/zabbix/zabbix_agentd.pid
agent_logfile: /var/log/zabbix/zabbix_agentd.log
agent_logfilesize: 100
agent_debuglevel: 3
agent_sourceip:

# visudo
# Example lines that could be used in sudoers file:
# allow remote commands to be sent by zabbix server and executed on the client
# allows 'zabbix' user to run all commands without password.
# zabbix ALL=NOPASSWD: ALL
# OR
# allows 'zabbix' user to restart apache without password.
# zabbix ALL=NOPASSWD: /etc/init.d/apache restart
agent_enableremotecommands: 1 
agent_logremotecommands: 1
#
agent_startagents: 3
#
agent_hostname: "{{ inventory_hostname }}"
agent_hostnameitem:
agent_hostmetadata:
agent_hostmetadataitem:
agent_refreshactivechecks: 120
agent_buffersend: 5
agent_buffersize: 100
agent_maxlinespersecond: 100
agent_allowroot: 0
agent_zabbix_alias:
agent_timeout: 3
agent_include: /etc/zabbix/zabbix_agentd.d
agent_unsafeuserparameters: 0
agent_userparameter:
agent_loadmodulepath: ${libdir}/modules
agent_loadmodule:

# TLS settings
agent_tlsconnect:
agent_tlsaccept:
agent_tlscafile:
agent_tlscrlfile:
agent_tlsservercertissuer:
agent_tlsservercertsubject:
agent_tlscertfile:
agent_tlskeyfile:
agent_tlspskidentity:
agent_tlspskfile:
